pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
     - author=dependabot[bot]
     - status-success=GitGuardian Security Checks
    actions:
     merge:
      method: merge