name: Heroku Update

on:
  workflow_dispatch:
#  push:
#    branches: [ master ]
#   pull_request:
#     branches: [ master ]

# Heroku will stop free dyno after November 28, 2022. I will leave config here for anyone need it.
env:
  APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
  API_KEY: ${{ secrets.HEROKU_API_KEY }}
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add api remote origin
      run: git remote add $APP_NAME "https://heroku:${API_KEY}@git.heroku.com/${APP_NAME}.git"
    - name: Update server to Heroku
      run: git push --force $APP_NAME `git subtree split --prefix server HEAD`:master
